* {
	margin: 0;
	padding: 0;
	outline: none!important;
	word-wrap: break-word !important;
	font-family: 'Montserrat', sans-serif;
	font-weight: normal;
	/* Support for all WebKit browsers. */
	-webkit-font-smoothing: antialiased;
	/* Support for Safari and Chrome. */
	text-rendering: optimizeLegibility;
	/* Support for Firefox. */
	-moz-osx-font-smoothing: grayscale;
	/* Support for IE. */
	font-feature-settings: 'liga';
	box-sizing: border-box;
}

:root {
	--primary 		: #ffffff; /*white*/
	--secondary 	: #000000; /*black*/
	--tertiary 		: #cccccc; /*grey*/
	--quaternary 	: #f1f1f1; /*lilywhite*/
	--quinary 		: #808080; /*50% Black*/
}

img {
	width: 100%;
	max-width: 100%;
	display: block;
}

a {
	text-decoration: none;
	color: var(--secondary);
}

.wrap {
	width: 960px;
	max-width: 90%;
	margin: auto;
}

ul {
	list-style-type: none;
}

body {
	font-size: 16px;
	color: var(--secondary);
	line-height: 1.6;
}
@media screen and (max-width: 900px) {
	body {
		font-size: 14px;
		line-height: 1.4;
	}
}

header {
	position: fixed;
	z-index: 100;
	background-color: var(--primary);
	top: 0;
	left: 0;
	width: 100%;
	border-bottom: 1px solid var(--tertiary);
	line-height: 0;
	/*overflow: hidden;*/
}
header .grid {
	position: relative;
	display: grid;
	grid-template-columns: auto 1fr;
	grid-gap: 20px;
	color: var(--secondary);
}
header .menu-icon {
	display: none;
}
header .grid .logo {
	height: 70px;
	display: flex;
}
header .grid .logo img {
	max-width: 180px;
	display: block;
	margin: auto;
}
header .grid .menu {
	height: 70px;
	display: flex;
	width: 100%;
	text-align: right;
}
header .grid .menu ul {
	display: block;
	margin: auto;
	width: 100%;
}
header .grid .menu ul li {
	display: inline-block;
	transition-duration: .5s;
}
header .grid .menu ul li span {
	padding: 24px 10px;
	cursor: pointer;
	font-size: 80%;
	font-weight: bold;
	text-transform: uppercase;
}
header .grid .menu ul li span:hover {
	border-bottom: 4px solid var(--quinary);
	color: var(--quinary);
}

/*.nav-highlight {
	padding-left: 10px;
}
.highlight {
	background-color: var(--secondary);
	color: var(--quaternary);
	padding: 10px 15px;
	border-radius: 50px;
}
.nav-highlight:hover .highlight {
	background-color: var(--quinary);
	color: var(--quaternary);
	transition-duration: .5s;
	border: none;
}*/
@media screen and (max-width: 900px) {
	header .grid {}

	header .menu-icon {
		display: flex;
		height: 70px;
		text-align: right;
	}

	header .menu-icon span {
		display: block;
		margin: auto;
		margin-right: 0;
		font-size: 24px;
		font-weight: bold;
	}

	header .grid .menu {
		position: absolute;
		width: 280px;
		top: 90%;
		right: 0;
		background-color: var(--quaternary);
		height: auto;
		transition-duration: 1s;
		opacity: 0;
	}

	header .grid .menu-icon:focus .menu {
		top: 100%;
		opacity: 1;
	}

	header .grid .menu ul,
	header .grid .menu ul li {
		display: block;
	}

	header .grid .menu ul li span {
		display: block;
		color: var(--secondary);
		padding: 20px 0;
		text-align: center;
		border-bottom: 1px solid var(--quinary);
	}
	header .grid .menu ul li span:hover {
		border-bottom: 1px solid var(--quinary);

	}

}


section {
	height: auto;
	background-color: var(--quaternary);

}
section.cover {
	width: 100%;
	max-height: 100%;
	text-align: center;
	padding-top: 71px;
}
section.cover .wrap {
	display: flex;
	width: 100%;
	max-width: 100%;
	height: calc(100vh - 90px);
	background: url(img/bg-home.jpg);
	background-repeat: no-repeat;
	background-size: cover;
	color: var(--quaternary);
	text-align: center;
}
section.cover .wrap span.text-cover {
	display: block;
	margin: auto;
}
section.cover .wrap span.text-cover h1 {
	font-size: 35px;
	font-weight: bold;
	text-transform: uppercase;
	letter-spacing: 2px;
}
section.cover .wrap span.text-cover p {
	font-size: 18px;
	letter-spacing: 2px;
}
section.cover .wrap span.text-cover button {
	padding: 10px 30px;
	border: 1px solid var(--primary);
	background-color: transparent;
	border-radius: 5px;
	color: var(--primary);
	cursor: pointer;
}
section.cover .wrap span.text-cover button:hover {
	background-color: var(--primary);
	color: var(--secondary);
	transition-duration: 1s;
}


main.tentang {
	padding: 50px 0;
	background-color: var(--primary);
	color: var(--secondary);
}
main.tentang .wrap .grid {
	display: grid;
	grid-template-columns: 1fr auto;
	grid-gap: 50px;
}
main.tentang .wrap .grid .flex {
	display: flex;
}
main.tentang .wrap .grid .flex .wrapper {
	margin: auto;
}
main.tentang .wrap .grid .flex .wrapper h2 {
	margin-bottom: 20px;
	font-weight: bold;
}
main.tentang .wrap .grid .flex .wrapper p {
	margin-bottom: 20px;
	font-size: 90%;
	text-align: justify;
}
main.tentang .wrap .grid .flex .wrapper img {
	width: 350px;
}


section.struktur {
	min-height: 100vh;
	background-color: var(--tertiary);
	padding: 30px 0;
}
section.struktur .wrap h2 {
	font-weight: bold;
}
section.struktur .wrap hr {
	border: 1px solid var(--quinary);
}
section.struktur .wrap .grid {
	display: grid;
	grid-gap: 20px;
	line-height: 1.5;
}
section.struktur .wrap .grid .item {
	background-color: var(--primary);
	box-shadow: 0 3px 7px var(--quinary);
}
section.struktur .wrap .grid .item .thumb {
	display: grid;
	grid-template-columns: 1fr auto;
	padding: 10px;
}
section.struktur .wrap .grid .item .thumb .title {
	font-size: 90%;
	text-align: left;
}
section.struktur .wrap .grid .item .thumb .title h3 {
	font-weight: bold;
}
section.struktur .wrap .grid .item .thumb .title p { 
	font-style: 'Arial', sans-serif;
}
section.struktur .wrap .grid .item .thumb .action {
	display: grid;
	grid-template-columns: repeat(3,auto);
	grid-gap: 15px;
	position: relative;
	float: right;
	text-align: left;
	font-size: 24px;
}
section.struktur .wrap .grid .item .thumb .action a {
	margin: auto;
	height: 10px;
	color: var(--quinary);
	text-align: center;

}
section.struktur .wrap .grid .item .thumb .action a:hover {
	color: var(--secondary);
	transition: all linear .5s;
}
section.struktur .wrap .grid .item .thumb .action a.div-link {
	position: absolute !important;
	bottom: 0;
	right: 0;
	width: 80px !important;
	height: auto !important;
	padding: 5px 0;
	background-color: var(--quinary);
	color: var(--primary);
	text-align: center;
	border-radius: 3px;
	font-size: 11px;
	letter-spacing: .5pt;
}
section.struktur .wrap .grid .item .thumb .action a.div-link:hover {
	background-color: var(--secondary);
	transition: all linear .5s;
}

section.struktur .wrap .observer {
	grid-template-columns: repeat(2,1fr);
	padding: 30px 0;
}
section.struktur .wrap .head {
	grid-template-columns: repeat(3,1fr);
}
section.struktur .wrap .divisi {
	grid-template-columns: repeat(4,1fr);
	padding: 30px 0;
}


section.divDesk {
	padding: 50px 0;
	background-color: var(--primary);
	color: var(--secondary);
}
section.divDesk .wrap .grid {
	display: grid;
	grid-template-columns: auto 1fr;
	grid-gap: 20px;
}
section.divDesk .wrap .grid .flex {
	display: flex;
}
section.divDesk .wrap .grid .flex .wrapper {
	margin: auto;
}
section.divDesk .wrap .grid .flex .wrapper img {
	width: 450px;
}
section.divDesk .wrap .grid .flex .wrapper h2 {
	margin-bottom: 5px;
	font-weight: bold;
}
section.divDesk .wrap .grid .flex .wrapper p {
	margin-bottom: 20px;
	font-size: 90%;
	text-align: justify;
}
section.divDesk .wrap .grid .flex .wrapper .divHead .item {
	background-color: var(--primary);
	box-shadow: 0 3px 7px var(--quinary);
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb {
	display: grid;
	grid-template-columns: 1fr auto;
	padding: 10px;
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .title {
	font-size: 90%;
	text-align: left;
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .title h3 {
	font-weight: bold;
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .title p { 
	font-style: 'Arial', sans-serif;
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .action {
	display: grid;
	grid-template-columns: repeat(3,auto);
	grid-gap: 10px;
	position: relative;
	float: right;
	text-align: left;
	font-size: 24px;
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .action a {
	margin: auto;
	height: 10px;
	color: var(--quinary);
	text-align: center;

}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .action a:hover {
	color: var(--secondary);
	transition: all linear .5s;
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .action a.div-link {
	position: absolute !important;
	bottom: 0;
	right: 0;
	width: 80px !important;
	height: auto !important;
	padding: 5px 0;
	background-color: var(--quinary);
	color: var(--primary);
	text-align: center;
	border-radius: 3px;
	font-size: 11px;
	letter-spacing: .5pt;
}
section.divDesk .wrap .grid .flex  .wrapper .divHead .item .thumb .action a.div-link:hover {
	background-color: var(--secondary);
	transition: all linear .5s;
}

section.divDesk .wrap .grid .flex  .wrapper .divHead {
	grid-template-columns: repeat(2,1fr);
	padding: 0;
}
section.divDesk .wrap .deskripsi {
	display: block;
}

section.divDesk .wrap .deskripsi ul {
	display: grid;
	grid-template-columns: auto auto;
	text-align: right;
	float: right;
}
section.divDesk .wrap .deskripsi ul li {
	float: right;
	text-align: right;
	text-transform: uppercase;
	font-size: 90%;
	padding: 10px;
	background-color: var(--quaternary);
}
li.active {
	font-weight: bold;
	border: 1px solid lightgrey;
	border-bottom: none;
	background-color: var(--primary) !important;
}

section.divDesk .wrap .deskripsi hr {
	margin-top: 21px;
}
section.divDesk .wrap .deskripsi .divStruktur {
	grid-template-columns: repeat(4,1fr);
	height: 100%;
}

section.divDesk .wrap .deskripsi .grid {
	display: grid;
	grid-gap: 20px;
	line-height: 1.5;
}
section.divDesk .wrap .deskripsi .grid .item {
	background-color: var(--primary);
	box-shadow: 0 3px 7px var(--quinary);
}
section.divDesk .wrap .deskripsi .grid .item .thumb {
	display: grid;
	grid-template-columns: 1fr auto;
	padding: 10px;
}
section.divDesk .wrap .deskripsi .grid .item .thumb .title {
	font-size: 80%;
	text-align: left;
}
section.divDesk .wrap .deskripsi .grid .item .thumb .title h3 {
	font-weight: bold;
}
section.divDesk .wrap .deskripsi .grid .item .thumb .title p { 
	font-style: 'Arial', sans-serif;
}
section.divDesk .wrap .deskripsi .grid .item .thumb .action {
	display: grid;
	grid-template-columns: repeat(3,auto);
	grid-gap: 15px;
	position: relative;
	float: right;
	text-align: left;
	font-size: 24px;
}
section.divDesk .wrap .deskripsi .grid .item .thumb .action a {
	margin: auto;
	height: 10px;
	color: var(--quinary);
	text-align: center;

}
section.divDesk .wrap .deskripsi .grid .item .thumb .action a:hover {
	color: var(--secondary);
	transition: all linear .5s;
}
section.divDesk .wrap .deskripsi .grid .item .thumb .action a.div-link {
	position: absolute !important;
	bottom: 0;
	right: 0;
	width: 80px !important;
	height: auto !important;
	padding: 5px 0;
	background-color: var(--quinary);
	color: var(--primary);
	text-align: center;
	border-radius: 3px;
	font-size: 11px;
	letter-spacing: .5pt;
}
section.divDesk .wrap .deskripsi .grid .item .thumb .action a.div-link:hover {
	background-color: var(--secondary);
	transition: all linear .5s;
}



section.kontak {
	padding: 30px 0;
	background-color: var(--primary);
	color: var(--secondary);
	border-top: 1px solid var(--tertiary);
}

section.kontak .wrap .grid {
	display: grid;
	grid-template-columns: 1fr auto 1fr; 
	grid-gap: 150px;
}

section.kontak .wrap .grid .flex {
	font-size: 90%;

}

section.kontak .wrap .grid .flex h2 {
	font-family: 'Arial',sans-serif;
	font-style: italic;
	font-weight: bold;
}

section.kontak .wrap .grid .address img {
	width: 150px;
}

section.kontak .wrap .grid .address p {
	text-align: justify;
	font-size: 90%;
}
section.kontak .wrap .grid .address a {
	float: right;
	font-family: 'Times New Roman',Times,serif !important;
	font-style: oblique;
	text-decoration: underline;
	color: var(--quinary);
}
section.kontak .wrap .grid .contact {
	
}

section.kontak .wrap .grid .contact .item {
	font-size: 90%;
	margin: auto;
}

section.kontak .wrap .grid .contact .item i {
	font-size: 18px;
	padding-right: 10px;
}

section.kontak .wrap .grid .follow {

}

section.kontak .wrap .grid .follow .item {
	display: grid;
	grid-template-columns: repeat(3,auto) 1fr;
	grid-gap: 15px;
	font-size: 25px;
}

footer {
	height: 35px;
	text-align: center;
	background-color: var(--quaternary);
	color: var(--quinary);
	padding: 5px 0;
	font-size: 14px;
	font-weight: normal;
}
